// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLhPzySrKgQJkFGmbrpa75WPlkUXtbX8',
    appId: '1:798075351606:web:18be23bbec28fe65fd9e97',
    messagingSenderId: '798075351606',
    projectId: 'taxiapp-69c0d',
    authDomain: 'taxiapp-69c0d.firebaseapp.com',
    databaseURL: 'https://taxiapp-69c0d-default-rtdb.firebaseio.com',
    storageBucket: 'taxiapp-69c0d.appspot.com',
    measurementId: 'G-C6DCGWS00K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9UuMetcfUqjj5JxLln4z31obSdKAfuw',
    appId: '1:798075351606:android:974068a16571eb74fd9e97',
    messagingSenderId: '798075351606',
    projectId: 'taxiapp-69c0d',
    databaseURL: 'https://taxiapp-69c0d-default-rtdb.firebaseio.com',
    storageBucket: 'taxiapp-69c0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-CA8w04l76yqhXWXMwF8JfFyKr_yWlQ',
    appId: '1:798075351606:ios:d681682723f4af71fd9e97',
    messagingSenderId: '798075351606',
    projectId: 'taxiapp-69c0d',
    databaseURL: 'https://taxiapp-69c0d-default-rtdb.firebaseio.com',
    storageBucket: 'taxiapp-69c0d.appspot.com',
    iosClientId: '798075351606-5on1co5455nb4i4r7hhk43f1dmluv5qd.apps.googleusercontent.com',
    iosBundleId: 'com.phongltktv.taxiFlutterApp',
  );
}
